# Generated by Django 5.1.4 on 2025-01-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retraite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraiteDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDeces', models.DateField()),
                ('dateDeclaration', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('AssignationDefunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retraite.prefecture')),
                ('retraite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retraite.retraite')),
            ],
        ),
    ]
