# Generated by Django 5.1.4 on 2025-01-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retraite', '0002_retraitedeces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBanque', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='retraitedeces',
            name='AssignationDefunt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retraite.prefecture'),
        ),
        migrations.AlterField(
            model_name='retraitedeces',
            name='retraite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retraite.retraite'),
        ),
        migrations.CreateModel(
            name='RetraiteVirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_RIB', models.CharField(max_length=150)),
                ('modePaiement', models.CharField(max_length=10)),
                ('echeancePremierVrmt', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('codeBanque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retraite.banque')),
                ('retraite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retraite.retraite')),
            ],
        ),
    ]
