# Generated by Django 5.1.4 on 2025-01-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retraite', '0005_alter_retraite_mensueldu_alter_retraite_allocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancesRetraite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateecheance', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
